// Mocks generated by Mockito 5.0.9 from annotations
// in gather_town_service/test/test-doubles/mocks/googleapis.dart.
// Do not manually edit this file.

import 'package:googleapis/secretmanager/v1.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeProjectsResource extends _i1.Fake implements _i2.ProjectsResource {}

/// A class which mocks [SecretManagerApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecretManagerApi extends _i1.Mock implements _i2.SecretManagerApi {
  MockSecretManagerApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProjectsResource get projects =>
      (super.noSuchMethod(Invocation.getter(#projects),
          returnValue: _FakeProjectsResource()) as _i2.ProjectsResource);
}
