name: Build & deploy container.

on:
  push:
    branches:
      - main

jobs:

  # the below is from enspyrco monorepo's CI that builds and deploys ci-tools 
  # container, but it uses dockerhub and I think we need to use google's 
  # container registry for "cloud build"

  # push_to_registry:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2
      
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push Container image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: containers/ci-tools/Dockerfile
  #         push: true
  #         tags: enspyrco/ci-tools:stable
