name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: npm ci
      - run: npm run build
      - run: npm test
